---
- hosts: me3800
  connection: local
  gather_facts: no
  tasks:
  - napalm_get_facts:
      optional_args: {'secret': "{{ ansible_ssh_pass }}"}
      dev_os: "{{ ansible_device_os }}"
      filter: arp_table
