---
- hosts: me3800
  connection: local
  gather_facts: no
  tasks:
  - name: show running-config
    ios_command:
      commands: show running-config
      authorize: yes
      auth_pass: "{{ansible_ssh_pass}}"
    register: show

  - debug: var=show.stdout_lines
